// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdzBsQCmL6No0qN9YpEiUFHepVB_jA3Os',
    appId: '1:76564238547:web:917487b42c364bb3374426',
    messagingSenderId: '76564238547',
    projectId: 'com-linikerthiers-firebase-app',
    authDomain: 'com-linikerthiers-firebase-app.firebaseapp.com',
    storageBucket: 'com-linikerthiers-firebase-app.firebasestorage.app',
    measurementId: 'G-WNJD8HB9DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtnsd9hGbed2dXEaQ7a2RkhrnKcyLLiXE',
    appId: '1:76564238547:android:8c78e672ed175be7374426',
    messagingSenderId: '76564238547',
    projectId: 'com-linikerthiers-firebase-app',
    storageBucket: 'com-linikerthiers-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84Xzk3ZYGU_tAEKl0qBakjDlWAc31rr8',
    appId: '1:76564238547:ios:815edd39270f408c374426',
    messagingSenderId: '76564238547',
    projectId: 'com-linikerthiers-firebase-app',
    storageBucket: 'com-linikerthiers-firebase-app.firebasestorage.app',
    iosBundleId: 'com.linikerthiers.firebaseapp.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84Xzk3ZYGU_tAEKl0qBakjDlWAc31rr8',
    appId: '1:76564238547:ios:815edd39270f408c374426',
    messagingSenderId: '76564238547',
    projectId: 'com-linikerthiers-firebase-app',
    storageBucket: 'com-linikerthiers-firebase-app.firebasestorage.app',
    iosBundleId: 'com.linikerthiers.firebaseapp.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdzBsQCmL6No0qN9YpEiUFHepVB_jA3Os',
    appId: '1:76564238547:web:0355af0b17ad9f0d374426',
    messagingSenderId: '76564238547',
    projectId: 'com-linikerthiers-firebase-app',
    authDomain: 'com-linikerthiers-firebase-app.firebaseapp.com',
    storageBucket: 'com-linikerthiers-firebase-app.firebasestorage.app',
    measurementId: 'G-YLSG1G29FZ',
  );

}